# Generated by Django 4.0.4 on 2022-05-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_alter_paths_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paths',
            name='root',
        ),
    ]
