# Generated by Django 4.0.4 on 2022-05-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_remove_paths_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='paths',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paths.paths'),
            preserve_default=False,
        ),
    ]
