# Generated by Django 4.0.4 on 2022-05-22 19:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('specs', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static/files/'), upload_to='')),
            ],
        ),
    ]
