# Generated by Django 4.0.4 on 2022-05-22 21:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='specs',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/statics/files/'), upload_to=''),
        ),
    ]
