# Generated by Django 4.0.4 on 2022-05-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_files_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='specs',
            field=models.FileField(upload_to='specs'),
        ),
    ]
