# Generated by Django 4.0.4 on 2022-05-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
        ('files', '0004_alter_files_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='path',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paths.paths'),
            preserve_default=False,
        ),
    ]
